### ISSUE TITLE
Weird flesh

### ISSUE THREAD

**Issue by kuyin** [EvelynSchwab/Chaos-flesh-meat-cube#1]
It's just shrink like this.
![image](https://github.com/EvelynSchwab/Chaos-flesh-meat-cube/assets/7321275/6393f729-2e6e-4fa8-8c0f-309c48b29371)

**Comment by EvelynSchwab** [comment]
This was caused by an inconsistency in the skeletal mesh surface and the surface bindings for the tetrahedral mesh, fixed in https://github.com/EvelynSchwab/Chaos-flesh-meat-cube/commit/8bc01993c76722f30ac65daa2f78318c2ac567e4
